name: 🛩️ New Aircraft Request
description: Request to add a new aircraft to the fleet configuration
title: "[Aircraft Request] "
labels: ["aircraft", "enhancement"]
assignees:
  - aerocaribbeanva

body:
  - type: markdown
    attributes:
      value: |
        ## New Aircraft Request
        Fill out the form below. Once submitted, a staff member will review and add the
        `aircraft-ready` label to trigger the automated addition workflow.

        The workflow will validate weights against local data and the SimBrief database.
        If the aircraft is **not** found in SimBrief, provide a custom profile URL below.

  - type: input
    id: aircraft_icao
    attributes:
      label: Aircraft ICAO Code
      description: Standard ICAO aircraft type designator (e.g., B738, A20N)
      placeholder: "B738"
    validations:
      required: true

  - type: input
    id: aircraft_name
    attributes:
      label: Aircraft Full Name
      description: Complete aircraft name (e.g., Boeing 737-800, Airbus A320neo)
      placeholder: "Boeing 737-800"
    validations:
      required: true

  - type: dropdown
    id: aircraft_type
    attributes:
      label: Aircraft Type
      description: Passenger or Freighter configuration
      options:
        - Passenger (J)
        - Freighter (F)
        - Both (Combi)
    validations:
      required: true

  - type: input
    id: range_nm
    attributes:
      label: Range (Nautical Miles)
      description: Maximum range in nautical miles with typical payload
      placeholder: "2935"
    validations:
      required: true

  - type: input
    id: mtow_lbs
    attributes:
      label: MTOW - Maximum Takeoff Weight (lbs)
      description: Maximum certified takeoff weight in pounds
      placeholder: "174200"
    validations:
      required: true

  - type: input
    id: oew_lbs
    attributes:
      label: OEW - Operating Empty Weight (lbs)
      description: Empty weight including crew, fluids, and equipment in pounds
      placeholder: "91300"
    validations:
      required: true

  - type: input
    id: max_payload_lbs
    attributes:
      label: Maximum Payload (lbs)
      description: Maximum cargo/passenger weight capacity in pounds. Calculated automatically if not provided.
      placeholder: "46200"

  - type: input
    id: pax_capacity
    attributes:
      label: Passenger Capacity
      description: Total number of passenger seats. Leave blank for freighters.
      placeholder: "162"

  - type: input
    id: first_class_seats
    attributes:
      label: First Class Seats
      description: Number of first class seats. Leave as 0 if the aircraft has no first class cabin.
      placeholder: "0"

  - type: input
    id: business_class_seats
    attributes:
      label: Business Class Seats
      description: Number of business class seats. Economy is calculated automatically (Total - First - Business). Leave as 0 if no business class.
      placeholder: "0"

  - type: input
    id: simbrief_url
    attributes:
      label: Custom SimBrief Profile URL
      description: |
        Only needed if this aircraft is **not** in the standard SimBrief database.
        The workflow checks automatically — leave blank if unsure.
        Create a profile at https://dispatch.simbrief.com/ and share the URL here.
      placeholder: "https://dispatch.simbrief.com/airframes/share/XXXXXX_YYYYYYYYYYYY"

  - type: input
    id: source_url
    attributes:
      label: Weight Validation Source
      description: URL to an official source for the weight data (APM, manufacturer specs, Wikipedia, etc.)
      placeholder: "https://www.boeing.com/content/dam/boeing/boeingdotcom/commercial/airports/acaps/737.pdf"

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any other relevant information about this aircraft
      placeholder: |
        - Special performance characteristics
        - Operational limitations
        - Fleet integration notes

  - type: checkboxes
    id: validation
    attributes:
      label: Pre-submission Checklist
      description: Please verify before submitting
      options:
        - label: I have checked that this aircraft is not already in the configuration
          required: true
        - label: The range is expressed in nautical miles (NM)
          required: true
        - label: All weights are in pounds (lbs)
          required: true
