name: Run Python Script and Commit to PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'flights-generator/TOURS/**/legs.txt'
      - 'flights-generator/TOURS/**/config.csv'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run_and_commit:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    environment: flight-gen
    steps:
      - name: Checkout PR head branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run flight generator for changed tours
        env:
          AIRPORT_GAP_TOKEN: ${{ secrets.AIRPORT_GAP_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail

          # Ensure we have the base branch (e.g., main) to diff against
          git fetch --no-tags --depth=1 origin "${{ github.event.pull_request.base.ref }}"
          BASE_REF="origin/main"

          # List files changed between PR head and base branch
          CHANGED="$(git diff --name-only "$BASE_REF"...HEAD || true)"

          declare -A tours=()
          while IFS= read -r f; do
            [[ -z "${f:-}" ]] && continue
            # Match exactly the two required files under a 4-char dir
            if [[ "$f" =~ ^flights-generator/TOURS/([A-Za-z0-9]{4})/(legs\.txt|config\.csv)$ ]]; then
              tours["${BASH_REMATCH[1]}"]=1
            fi
          done <<< "$CHANGED"

          if [ ${#tours[@]} -eq 0 ]; then
            echo "No tour changes detected."
            exit 0
          fi

          pushd flights-generator >/dev/null
          for t in "${!tours[@]}"; do
            if [[ -f "TOURS/$t/legs.txt" && -f "TOURS/$t/config.csv" ]]; then
              echo "Generating flights for TOUR $t..."
              # Use --yes if you added it; otherwise pipe Y
              python generate_flights.py TOUR "$t" --yes
              # or: printf 'Y\n' | python generate_flights.py TOUR "$t"
            else
              echo "Skipping $t (missing legs.txt or config.csv)"
            fi
          done
          popd >/dev/null


      - name: Show git status (debug)
        run: |
          git status
          echo "---- DIFF (unstaged) ----"
          git diff -- .github/ci/last-run.txt || true

      - name: Commit and push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          echo "About to commit:"
          git diff --cached --name-only
          git commit -m "Automated commit from workflow"
          git push
