name: Run Python Script and Commit to PR

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  run_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: echo "Hello from Github Actions" > test.txt

      - name: Force a detectable change (test)
        run: |
          mkdir -p .github/ci
          # Write a timestamp and a random suffix so the file always changes
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') $RANDOM" > .github/ci/last-run.txt
          cat .github/ci/last-run.txt

      - name: Show git status (debug)
        run: |
          git status
          echo "---- DIFF (unstaged) ----"
          git diff -- .github/ci/last-run.txt || true

      - name: Commit and push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Automated commit from workflow"
          git push
