name: Run Python Script and Commit to PR

on:
  pull_request:
    types: [opened]

jobs:
  run_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for authentication

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Specify your desired Python version

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # If your script has dependencies

      - name: Run Python script
        run: echo "Hello from Github Actions" >> test.txt # Replace with your script name

      - name: Configure Git and Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add . # Add any modified files
          git commit -m "Automated commit from Python script" || echo "No changes to commit"
          git push